## Recap your python skills

<div class='alert alert-warning'>
<h4>Ex0.1. Write a function `splitter` which inputs a string and breaks that string into substrings separated by `\`. </h4>
</div>
For instance

`splitter("C:\Users\Shrek")` 

should return the list

`["C:", "Users", "Shrek"]`


**Note:** You will have to find out yourself what string method to apply. Use whatever means possible (the Tab trick, the internet...) to find a solution.

**Hint:** you will likely get a formatting error, because `"\"` has a special function in string (escape character). Use a raw string instead: `r"\"`, or `"\\"`.

In [3]:
#example of basic string.split() functionality
st = "abc"
st.split('b')

['a', 'c']

In [ ]:
# Ex1


In [ ]:
# %load solutions/ex0_1.py

In [5]:
# run this to test your code
st = r"C:\Users\Shrek"
splitter(st)

['C:', 'Users', 'Shrek']

<div class='alert alert-warning'>

<h4>Ex0.2. Modify the function to be more flexible, so it can decide what kind of separator to use.</h4>
</div>


In [6]:
st.split??

In [ ]:
# Ex2


In [7]:
# %load solutions/ex0_2.py

<div class='alert alert-warning'>

<h4>Ex0.3. Modify the code to take not a single, but a list of strings and perform the action on each one of them.</h4>
    </div>

In [ ]:
# Ex3


In [8]:
# %load solutions/ex0_3.py

In [10]:
sts = [r"C:\Users\Shrek",
       r"C:\Users\Peder\Documents\repos\Seili-2020\machine-learning"]

multi_splitter(sts)

[['C:', 'Users', 'Shrek'],
 ['C:',
  'Users',
  'Peder',
  'Documents',
  'repos',
  'Seili-2020',
  'machine-learning']]

### Data representation, numpy and matrices
A dataset can usually be represented in a tabular format. The convenvtion is to have the rows representing an individual sample, and the columns are features. This corresponds to a matrix of shape rows x columns.

<img src="https://cdn.kastatic.org/googleusercontent/_anqPXDhdx2MuQIN7S9F-nYDbxNVMFfrKL-bgihYpi1iqa-bi5Gggwy8k70xZgZ0j84IzMKQDg2VusdRgoUens4" width="500" height="500" />

In [9]:
# numpy and pandas are two of the most ubiquitous python libraries, so get used to seeing this.
import pandas as pd #this is used for working with tables
import numpy as np #this is used for working with matrices and vectors

In [11]:
diabetes = 'data/diabetes.csv' # provide the path of the dataset
df = pd.read_csv(diabetes) # this loads the file into memory

print(type(df))

<class 'pandas.core.frame.DataFrame'>


In [12]:
df.head() # displays the 5 first rows

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DPedigreeFunc  Age  Class  
0          0.627   50      1  
1          0.351   31      0  
2          0.672   32      1  
3          0.167   21      0  
4          2.288   33      1

Note that the rightmost column represents the diagnosis (what we consider the target or label). This is our `y`.

The `values` attribute of a dataframe (table) returns the numpy matrix of the entries.

In [13]:
data = df.values
print(type(data))
data

<class 'numpy.ndarray'>


array([[  6.   , 148.   ,  72.   , ...,   0.627,  50.   ,   1.   ],
       [  1.   ,  85.   ,  66.   , ...,   0.351,  31.   ,   0.   ],
       [  8.   , 183.   ,  64.   , ...,   0.672,  32.   ,   1.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,   0.245,  30.   ,   0.   ],
       [  1.   , 126.   ,  60.   , ...,   0.349,  47.   ,   1.   ],
       [  1.   ,  93.   ,  70.   , ...,   0.315,  23.   ,   0.   ]])

In [14]:
# shape is a fundamental attribute of a matrix. The convention is (rows x cols). This is important!
print(data.shape)

# so the size (N) of the dataset is just
print(f"Sample size = {data.shape[0]}")

(768, 9)
Sample size = 768


Indexing works as follows for matrices (or tables):

In [16]:
# values of three first rows' first column
data[:3,0]

array([6., 1., 8.])

## 4. Building train_test_splitter from scratch.

![title](assets/Train_test_sets.jpg)

<div class='alert alert-warning'>

<h4>
Ex0.4a. Make a function which takes a number and a percentage as input, and returns that percentage of the given number.</h4>
    
**Note:** the output should be rounded to the closest integer.
    </div>

In [ ]:
# Ex4a


In [ ]:
# %load solutions/ex0_4a.py

<div class='alert alert-warning'>

<h4>Ex0.4b. Provided an array of indeces, make a function `data_splitter` which returns the rows corresponding to those indexes.</h4>

</div>

**Note** Function takes two parameters: data and index-array

In [ ]:
# Ex4b


In [ ]:
# %load solutions/ex0_4b.py
def data_splitter(data, idxs):
    subsample = data[idxs]
    return subsample

## Note: matrices are indexed like mat[rows, cols]. If only one is provided, it is interpreted as mat[rows].

In [ ]:
# for testing
indeces = np.array([0,2]) # select the first and third row
print(data_splitter(data, indeces))

<div class='alert alert-warning'>

<h4>Ex0.4c. Provided an integer N, write a function `get_indeces` which splits the numbers (0-N) into two non-overlapping subsets (e.g. training indeces and test indeces).</h4>

You should be able to call it like `get_indeces(N, p)`, where p is the proportion (between 0 and 1) determining the relative size of the training set.

**Hint:** start by creating a vector of the integers 0-N using `np.arange(N)`.
    </div>

In [ ]:
# Ex4c


In [ ]:
# %load solutions/ex0_4c.py


In [39]:
# test your implementation
get_indeces(10, .8)

(array([1, 7, 9, 6, 2, 8, 4, 0]), array([5, 3]))

**Problem:** what if the data is ordered based on label? Make the selection random.

<div class='alert alert-warning'>

<h4>Ex0.4d. Now chain it all together into a single train-test splitter -function tts().</h4>

It should take two inputs: the data matrix and p, and return two numpy arrays, one containing the training samples, one containing the test samples.
</div>
    
**Hint** Use get_indeces() and use indeces to get the actual values

In [ ]:
# Ex4d

In [ ]:
# %load solutions/ex0_4d.py

In [48]:
# test your implementation
train, test = tts(data)
print(train.shape,'\n',test.shape)

(576, 9) 
 (192, 9)


<div class='alert alert-warning'>

<h4>Ex0.4e. Final adjustment: we want to separate X from y also. Edit the function above to return the values X_train, y_train, X_test, y_test. </h4>

Remember that the label (y) is the last column.
</div>

In [ ]:
# Ex4e


In [50]:
# %load solutions/ex0_4e.py

In [51]:
# Run this to test. Do the results make sense?

X_train, X_test, y_train, y_test = tts(data)

for d in [X_train, y_train, X_test, y_test]:
    print(d.shape)

(576, 8)
(576,)
(192, 8)
(192,)
